spring:
  application:
    name: fondo-gateway
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: http://www.baidu.com:80/
          predicates:
            - Path=/test
server:
  port: 8081
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG